build:
  version: '1.0'

loans:
  message: "Welcome to fahimmohammed loans related prod APIs "
  contactDetails:
    name: "Fahim - Prod Support"
    email: "fahim00644@gmail.com"
  onCallSupport:
    - (+91) 9999999999
    - (+91) 9999999999