build:
  version: '3.0'

loans:
  message: "Welcome to fahimmohammed loans related local APIs "
  contactDetails:
    name: "Fahim - Developer"
    email: "fahim00644@gmail.com"
  onCallSupport:
    - (+91) 9999999999
    - (+91) 9999999999
